# Generated by Django 3.2 on 2021-04-11 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_distribution_centers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=20)),
                ('stock_cases', models.PositiveIntegerField()),
                ('stock_bottles', models.PositiveIntegerField()),
                ('next_arrival_date', models.DateTimeField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=20)),
                ('stock_cases', models.PositiveIntegerField()),
                ('stock_bottles', models.PositiveIntegerField()),
                ('next_arrival_date', models.DateTimeField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_wine_colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_wines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=120)),
                ('bottle_size', models.IntegerField()),
                ('case_capacity', models.IntegerField()),
                ('case_cost', models.PositiveIntegerField()),
                ('bottle_cost', models.PositiveIntegerField()),
                ('indicator', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('color', models.ManyToManyField(to='warehouse.tbl_wine_colors')),
                ('country', models.ManyToManyField(to='warehouse.tbl_country')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.tbl_customers')),
                ('distribution_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.tbl_distribution_centers')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_distribution_centers',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.tbl_warehouse'),
        ),
    ]
