# Generated by Django 3.2 on 2021-04-13 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20210413_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_order_items',
            name='availablity',
            field=models.CharField(default='In stock', max_length=100),
        ),
        migrations.AddField(
            model_name='tbl_order_items',
            name='delivery_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
