# Generated by Django 3.2 on 2021-04-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20210413_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_order_items',
            name='frequency',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
