# Generated by Django 3.2 on 2021-04-13 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_tbl_orders_delivery_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shopping_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_charge', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.tbl_customers')),
                ('distribution_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.tbl_distribution_centers')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_shopping_bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_charge', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.tbl_customers')),
                ('distribution_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.tbl_distribution_centers')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_order_items',
            name='bucket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.tbl_shopping_bucket'),
        ),
        migrations.AddField(
            model_name='tbl_order_items',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.tbl_shopping_list'),
        ),
    ]
